//
// Created by kolya on 06.01.2023.
//

#ifndef DINING_PHILOSOPHERS_PROBLEM_DEFINESUTIL_H
#define DINING_PHILOSOPHERS_PROBLEM_DEFINESUTIL_H

#define PHILOSOPHER_NAME "PHIL_NUM_"

#endif //DINING_PHILOSOPHERS_PROBLEM_DEFINESUTIL_H
