//
// Created by kolya on 06.01.2023.
//

#ifndef DINING_PHILOSOPHERS_PROBLEM_REQUESTTYPE_H
#define DINING_PHILOSOPHERS_PROBLEM_REQUESTTYPE_H

enum class RequestType {
    GET_FORK,
    RETURN_FORKS
};

#endif //DINING_PHILOSOPHERS_PROBLEM_REQUESTTYPE_H
